exclude: '^docs/conf.py'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
    args: ['--remove']
  - id: name-tests-test
  - id: no-commit-to-branch
    args: ['--branch', 'main', '--pattern', 'release/*']
  - id: mixed-line-ending
    args: ['--fix=lf']  # enforce Linux(/Mac) line endings

- repo: https://github.com/PyCQA/isort
  rev: 5.7.0
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.8.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-no-eval
  - id: python-no-log-warn
  - id: python-use-type-annotations
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/asottile/blacken-docs
  rev: v1.8.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black]
